/*
 * Copyright (c) 2025 Johan Stenstam, johan.stenstam@internetstiftelsen.se
 */
package cli

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	tdns "github.com/johanix/tdns/v2"
	tdnscli "github.com/johanix/tdns/v2/cli"
	"github.com/miekg/dns"
	"github.com/ryanuber/columnize"
	"github.com/spf13/cobra"
)

// The agent's "zone" subtree. tdns-mp owns the whole subtree (NewAgentZoneCmd
// below): until 2026-09 the mp-specific leaves were pushed into tdns's static
// AgentZoneCmd from init(), which left the tree with two reload/write/update/
// readfake/dsync children (one from each package) and made a second instance
// impossible, since a static command has exactly one parent.

func newAgentZoneMPListCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "mplist",
		Short: "List multi-provider zones with HSYNCPARAM details",
		Run:   func(cmd *cobra.Command, args []string) { runZoneMPList(cmd, args) },
	}
	return c
}

// agentZoneBumpCmd forces a SOA serial increase on an agent-served
// zone. The agent serves autogenerated zones (no zonefile to edit),
// so this is the only way to force propagation to secondaries after
// an in-place change. The agent /zone endpoint already handles the
// "bump" command (APIzone, registered for AppTypeAgent); only this
// CLI subcommand was missing. Reuses tdns's RunZoneBump, exactly as
// signer/combiner zone bump do via NewZoneCmd.
func newAgentZoneBumpCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "bump",
		Short: "Bump the SOA serial of an agent-served zone",
		Run:   func(cmd *cobra.Command, args []string) { tdnscli.RunZoneBump(RoleForCmd(cmd), args) },
	}
	return c
}

func runZoneMPList(cmd *cobra.Command, args []string) {
	api, err := GetApiClientForCmd(cmd, true)
	if err != nil {
		log.Fatalf("Error getting API client for %s: %v", RoleForCmd(cmd), err)
	}

	resp, err := SendMPListCommand(api)
	if err != nil {
		fmt.Printf("Error: %s\n", err.Error())
		os.Exit(1)
	}

	ListMPZones(resp)
}

func newAgentZoneReloadCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "reload",
		Short: "Request re-loading a zone",
		Run: func(cmd *cobra.Command, args []string) {
			if tdns.Globals.Zonename == "" {
				fmt.Printf("Error: zone name not specified. Terminating.\n")
				os.Exit(1)
			}

			api, err := GetApiClientForCmd(cmd, true)
			if err != nil {
				log.Fatalf("Error getting API client: %v", err)
			}

			resp, err := tdnscli.SendZoneCommand(api, tdns.ZonePost{
				Command: "reload",
				Zone:    dns.Fqdn(tdns.Globals.Zonename),
				Force:   force,
			})

			if err != nil {
				fmt.Printf("Error from %q: %s\n", resp.AppName, err.Error())
				os.Exit(1)
			}

			if resp.Msg != "" {
				fmt.Printf("%s\n", resp.Msg)
			}
		},
	}
	return c
}

func newAgentZoneWriteCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "write",
		Short: "Write a zone to disk",
		Run: func(cmd *cobra.Command, args []string) {
			tdnscli.PrepArgs("childzone")

			api, err := GetApiClientForCmd(cmd, true)
			if err != nil {
				log.Fatalf("Error getting API client: %v", err)
			}

			cr, err := tdnscli.SendZoneCommand(api, tdns.ZonePost{
				Command: "write-zone",
				Zone:    tdns.Globals.Zonename,
				Force:   force,
			})
			if err != nil {
				fmt.Printf("Error from %q: %s\n", cr.AppName, err.Error())
				os.Exit(1)
			}

			if cr.Msg != "" {
				fmt.Printf("%s\n", cr.Msg)
			}
		},
	}
	return c
}

func newAgentZoneUpdateCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "update",
		Short: "Create and ultimately send a DNS UPDATE msg for zone auth data",
	}
	c.AddCommand(newAgentZoneUpdateCreateCmd(kind))
	return c
}

func newAgentZoneUpdateCreateCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "create",
		Short: "Create and ultimately send a DNS UPDATE msg for zone auth data",
		Long: `Will query for details about the DNS UPDATE via (add|del|show|set-ttl) commands.
When the message is complete it may be signed and sent by the 'send' command. After a
message has been send the loop will start again with a new, empty message to create.
Loop ends on the command "QUIT"

The zone to update is mandatory to specify on the command line with the --zone flag.`,
		Run: func(cmd *cobra.Command, args []string) {
			tdnscli.PrepArgs("zonename")
			tdnscli.CreateUpdate(RoleForCmd(cmd), "zone")
		},
	}
	c.Flags().StringVarP(&tdns.Globals.Zonename, "zone", "z", "", "Zone to update")
	tdnscli.AttachUpdateCreateFlags(c)
	return c
}

func newAgentZoneReadFakeCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "readfake",
		Short: "Create a fake zone from a compiled in string",
		Run: func(cmd *cobra.Command, args []string) {
			err := tdnscli.ReadZoneData(dns.Fqdn(tdns.Globals.Zonename))
			if err != nil {
				log.Fatalf("Error: %v", err)
			}
		},
	}
	return c
}

// --- Dsync subcommands ---

func newAgentZoneDsyncCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "dsync",
		Short: "Prefix command, not useable by itself",
	}
	c.AddCommand(newAgentZoneDsyncStatusCmd(kind), newAgentZoneDsyncBootstrapCmd(kind), newAgentZoneDsyncRollKeyCmd(kind), newAgentZoneDsyncPublishCmd(kind), newAgentZoneDsyncUnpublishCmd(kind))
	return c
}

func newAgentZoneDsyncStatusCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "status",
		Short: "Send dsync status command to tdns-auth",
		Run: func(cmd *cobra.Command, args []string) {
			tdnscli.PrepArgs("zonename")

			api, err := GetApiClientForCmd(cmd, true)
			if err != nil {
				log.Fatalf("Error getting API client: %v", err)
			}

			resp, err := tdnscli.SendDsyncCommand(api, tdns.ZoneDsyncPost{
				Command: "status",
				Zone:    dns.Fqdn(tdns.Globals.Zonename),
			})

			if err != nil {
				fmt.Printf("Error: %s\n", err.Error())
				os.Exit(1)
			}
			if resp.Error {
				fmt.Printf("Error from tdns-auth: %s\n", resp.ErrorMsg)
				os.Exit(1)
			}

			if resp.Msg != "" {
				fmt.Printf("%s\n", resp.Msg)
			}
			out := []string{}
			for key, status := range resp.Functions {
				out = append(out, fmt.Sprintf("%s|%s", key, status))
			}

			sort.Strings(out)
			if tdns.Globals.ShowHeaders {
				out = append([]string{"Function|Status"}, out...)
			}

			fmt.Printf("%s\n", columnize.SimpleFormat(out))
			if len(resp.Todo) > 0 {
				fmt.Printf("\nTODO:\n")
				for _, todo := range resp.Todo {
					fmt.Printf("--> %s\n", todo)
				}
			}
		},
	}
	return c
}

func newAgentZoneDsyncBootstrapCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "bootstrap-sig0-key",
		Short: "Send dsync bootstrap command to tdns-auth",
		Run: func(cmd *cobra.Command, args []string) {
			tdnscli.PrepArgs("zonename", "algorithm")

			api, err := GetApiClientForCmd(cmd, true)
			if err != nil {
				log.Fatalf("Error getting API client: %v", err)
			}

			resp, err := tdnscli.SendDsyncCommand(api, tdns.ZoneDsyncPost{
				Command:   "bootstrap-sig0-key",
				Zone:      dns.Fqdn(tdns.Globals.Zonename),
				Algorithm: dns.StringToAlgorithm[tdns.Globals.Algorithm],
			})
			tdnscli.PrintUpdateResult(resp.UpdateResult)
			if err != nil {
				fmt.Printf("Error: %s\n", err.Error())
				os.Exit(1)
			}
			if resp.Error {
				fmt.Printf("Error from tdns-auth: %s\n", resp.ErrorMsg)
				os.Exit(1)
			}
			if resp.Msg != "" {
				fmt.Printf("%s\n", resp.Msg)
			}
		},
	}
	c.PersistentFlags().StringVarP(&tdns.Globals.Algorithm, "algorithm", "a", "ED25519", "Algorithm to use for the new SIG(0) key")
	return c
}

func newAgentZoneDsyncRollKeyCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "roll-sig0-key",
		Short: "Send dsync rollover command to tdns-auth",
		Run: func(cmd *cobra.Command, args []string) {
			tdnscli.PrepArgs("zonename", "algorithm", "rollaction")

			api, err := GetApiClientForCmd(cmd, true)
			if err != nil {
				log.Fatalf("Error getting API client: %v", err)
			}

			resp, err := tdnscli.SendDsyncCommand(api, tdns.ZoneDsyncPost{
				Command:   "roll-sig0-key",
				Zone:      dns.Fqdn(tdns.Globals.Zonename),
				Algorithm: dns.StringToAlgorithm[tdns.Globals.Algorithm],
				Action:    agentRollaction,
			})
			tdnscli.PrintUpdateResult(resp.UpdateResult)
			if err != nil {
				fmt.Printf("Error: %s\n", err.Error())
				os.Exit(1)
			}
			if resp.Error {
				fmt.Printf("Error from tdns-auth: %s\n", resp.ErrorMsg)
				os.Exit(1)
			}
			if resp.Msg != "" {
				fmt.Printf("%s\n", resp.Msg)
			}
		},
	}
	c.PersistentFlags().StringVarP(&tdns.Globals.Algorithm, "algorithm", "a", "ED25519", "Algorithm to use for the new SIG(0) key")
	c.PersistentFlags().StringVarP(&agentRollaction, "rollaction", "r", "complete", "[debug] Phase of the rollover to perform: complete, add, remove, update-local")
	c.PersistentFlags().MarkHidden("rollaction")
	return c
}

func newAgentZoneDsyncPublishCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "publish",
		Short: "Send dsync publish-dsync-rrset command to tdns-auth",
		Run: func(cmd *cobra.Command, args []string) {
			tdnscli.PrepArgs("zonename")

			api, err := GetApiClientForCmd(cmd, true)
			if err != nil {
				log.Fatalf("Error getting API client: %v", err)
			}

			resp, err := tdnscli.SendDsyncCommand(api, tdns.ZoneDsyncPost{
				Command: "publish-dsync-rrset",
				Zone:    dns.Fqdn(tdns.Globals.Zonename),
			})
			if err != nil {
				fmt.Printf("Error: %s\n", err.Error())
				os.Exit(1)
			}
			if resp.Error {
				fmt.Printf("Error from tdns-auth: %s\n", resp.ErrorMsg)
				os.Exit(1)
			}
			if resp.Msg != "" {
				fmt.Printf("%s\n", resp.Msg)
			}
		},
	}
	return c
}

func newAgentZoneDsyncUnpublishCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "unpublish",
		Short: "Send dsync unpublish-dsync-rrset command to tdns-auth",
		Run: func(cmd *cobra.Command, args []string) {
			tdnscli.PrepArgs("zonename")

			api, err := GetApiClientForCmd(cmd, true)
			if err != nil {
				log.Fatalf("Error getting API client: %v", err)
			}

			resp, err := tdnscli.SendDsyncCommand(api, tdns.ZoneDsyncPost{
				Command: "unpublish-dsync-rrset",
				Zone:    dns.Fqdn(tdns.Globals.Zonename),
			})
			if err != nil {
				fmt.Printf("Error: %s\n", err.Error())
				os.Exit(1)
			}
			if resp.Error {
				fmt.Printf("Error from tdns-auth: %s\n", resp.ErrorMsg)
				os.Exit(1)
			}
			if resp.Msg != "" {
				fmt.Printf("%s\n", resp.Msg)
			}
		},
	}
	return c
}

// --- New addrr/delrr commands ---

func newAgentZoneAddRRCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "addrr",
		Short: "Add a resource record to a zone and sync with peers and combiner",
		Long: `Add a resource record to the specified zone. Supported RR types: NS, DNSKEY, CDS, CSYNC, KEY.
The RR type is inferred from the --rr argument.

This will:
- Add the RR to the local synced data store
- Send sync operations to all remote agents for this zone
- Send the update to the combiner

Examples:
  tdns-cliv2 agent zone addrr --zone whisky.dnslab. --rr "whisky.dnslab. IN NS ns.alpha.dnslab."
  tdns-cliv2 agent zone addrr --zone whisky.dnslab. --rr "whisky.dnslab. 300 IN DNSKEY 257 3 13 <base64>"`,
		Run: func(cmd *cobra.Command, args []string) {
			tdnscli.PrepArgs("zonename")

			if agentZoneRR == "" {
				log.Fatalf("Error: --rr flag is required")
			}

			rr, err := dns.NewRR(agentZoneRR)
			if err != nil {
				log.Fatalf("Error: Invalid DNS record: %v", err)
			}

			if !allowedLocalRRtypes[rr.Header().Rrtype] {
				allowed := allowedRRtypeNames()
				log.Fatalf("Error: RR type %s is not allowed (must be one of: %s)",
					dns.TypeToString[rr.Header().Rrtype], strings.Join(allowed, ", "))
			}

			if dns.Fqdn(rr.Header().Name) != dns.Fqdn(tdns.Globals.Zonename) {
				log.Fatalf("Error: Record owner (%s) must match zone (%s)", rr.Header().Name, tdns.Globals.Zonename)
			}

			agentZoneForce, _ := cmd.Flags().GetBool("force")
			req := AgentMgmtPost{
				Command: "add-rr",
				Zone:    ZoneName(tdns.Globals.Zonename),
				RRs:     []string{rr.String()},
			}
			if agentZoneForce {
				req.Data = map[string]interface{}{"force": true}
			}

			api, err := GetApiClientForCmd(cmd, true)
			if err != nil {
				log.Fatalf("Error getting API client: %v", err)
			}

			_, buf, err := api.RequestNG("POST", "/agent", req, true)
			if err != nil {
				log.Fatalf("API request failed: %v", err)
			}
			var amr AgentMgmtResponse
			if err := json.Unmarshal(buf, &amr); err != nil {
				log.Fatalf("Failed to parse response: %v", err)
			}

			if amr.Error {
				log.Fatalf("Error: %s", amr.ErrorMsg)
			}

			rrtype := dns.TypeToString[rr.Header().Rrtype]
			fmt.Printf("Successfully added %s record to zone %s\n", rrtype, tdns.Globals.Zonename)
			fmt.Printf("  Record: %s\n", rr.String())
			if amr.Msg != "" {
				fmt.Printf("  %s\n", amr.Msg)
			}
		},
	}
	c.Flags().StringVarP(&agentZoneRR, "rr", "", "", "DNS record to add")
	c.Flags().Bool("force", false, "Bypass dedup check and always send transaction")
	return c
}

func newAgentZoneDelRRCmd(kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "delrr",
		Short: "Delete a resource record from a zone and sync with peers and combiner",
		Long: `Delete a resource record from the specified zone. Supported RR types: NS, DNSKEY, CDS, CSYNC, KEY.
The RR type is inferred from the --rr argument.

This will:
- Remove the RR from the local synced data store
- Send sync operations to all remote agents for this zone
- Send the update to the combiner

Examples:
  tdns-cliv2 agent zone delrr --zone whisky.dnslab. --rr "whisky.dnslab. IN NS ns.alpha.dnslab."
  tdns-cliv2 agent zone delrr --zone whisky.dnslab. --rr "whisky.dnslab. 300 IN DNSKEY 257 3 13 <base64>"`,
		Run: func(cmd *cobra.Command, args []string) {
			tdnscli.PrepArgs("zonename")

			if agentZoneRR == "" {
				log.Fatalf("Error: --rr flag is required")
			}

			rr, err := dns.NewRR(agentZoneRR)
			if err != nil {
				log.Fatalf("Error: Invalid DNS record: %v", err)
			}

			if !allowedLocalRRtypes[rr.Header().Rrtype] {
				allowed := allowedRRtypeNames()
				log.Fatalf("Error: RR type %s is not allowed (must be one of: %s)",
					dns.TypeToString[rr.Header().Rrtype], strings.Join(allowed, ", "))
			}

			if dns.Fqdn(rr.Header().Name) != dns.Fqdn(tdns.Globals.Zonename) {
				log.Fatalf("Error: Record owner (%s) must match zone (%s)", rr.Header().Name, tdns.Globals.Zonename)
			}

			agentZoneForce, _ := cmd.Flags().GetBool("force")
			req := AgentMgmtPost{
				Command: "del-rr",
				Zone:    ZoneName(tdns.Globals.Zonename),
				RRs:     []string{rr.String()},
			}
			if agentZoneForce {
				req.Data = map[string]interface{}{"force": true}
			}

			api, err := GetApiClientForCmd(cmd, true)
			if err != nil {
				log.Fatalf("Error getting API client: %v", err)
			}

			_, buf, err := api.RequestNG("POST", "/agent", req, true)
			if err != nil {
				log.Fatalf("API request failed: %v", err)
			}
			var amr AgentMgmtResponse
			if err := json.Unmarshal(buf, &amr); err != nil {
				log.Fatalf("Failed to parse response: %v", err)
			}

			if amr.Error {
				log.Fatalf("Error: %s", amr.ErrorMsg)
			}

			rrtype := dns.TypeToString[rr.Header().Rrtype]
			fmt.Printf("Successfully removed %s record from zone %s\n", rrtype, tdns.Globals.Zonename)
			fmt.Printf("  Record: %s\n", rr.String())
			if amr.Msg != "" {
				fmt.Printf("  %s\n", amr.Msg)
			}
		},
	}
	c.Flags().StringVarP(&agentZoneRR, "rr", "", "", "DNS record to delete")
	c.Flags().Bool("force", false, "Bypass dedup check and always send transaction")
	return c
}

// --- Helper ---

// allowedLocalRRtypes mirrors the "apex-combiner" preset from
// tdns-mp/v2/combiner_utils.go. Defined locally to avoid a
// circular import (cli → tdnsmp).
var allowedLocalRRtypes = map[uint16]bool{
	dns.TypeDNSKEY: true,
	dns.TypeCDS:    true,
	dns.TypeCSYNC:  true,
	dns.TypeNS:     true,
	dns.TypeKEY:    true,
}

func allowedRRtypeNames() []string {
	names := make([]string, 0, len(allowedLocalRRtypes))
	for rrtype := range allowedLocalRRtypes {
		names = append(names, dns.TypeToString[rrtype])
	}
	sort.Strings(names)
	return names
}

// --- Local variables for flags ---

var agentZoneRR string
var agentRollaction string

// --- init ---

// NewAgentZoneCmd builds the agent "zone" subtree. role is the target the
// tree resolves to (needed for the one leaf borrowed from tdns), kind the
// daemon kind; every other leaf resolves its target from the tree.
//
// --force/-F is persistent here because addrr/delrr read it through
// cmd.Flags() and reload/write pass it as ZonePost.Force; it used to be
// inherited from tdns's AgentZoneCmd.
func NewAgentZoneCmd(role, kind string) *cobra.Command {
	c := &cobra.Command{
		Use:   "zone",
		Short: "Agent zone management commands",
	}
	c.PersistentFlags().BoolVarP(&force, "force", "F", false, "force operation")
	c.AddCommand(
		tdnsZoneListCmd(role),
		newAgentZoneMPListCmd(kind),
		newAgentZoneBumpCmd(kind),
		newAgentZoneReloadCmd(kind),
		newAgentZoneWriteCmd(kind),
		newAgentZoneUpdateCmd(kind),
		newAgentZoneReadFakeCmd(kind),
		newAgentZoneDsyncCmd(kind),
		newAgentZoneAddRRCmd(kind),
		newAgentZoneDelRRCmd(kind),
		newAgentZoneEditsCmd(kind),
	)
	return c
}

// tdnsZoneListCmd is tdns's "zone list" leaf, lifted out of a fresh
// tdnscli.NewZoneCmd(role) so that it keeps the -f/-N/-P flags, which are
// bound to variables private to the tdns cli package that RunZoneList
// reads. It was the one leaf of tdns's static AgentZoneCmd that mp had no
// copy of.
func tdnsZoneListCmd(role string) *cobra.Command {
	tmp := tdnscli.NewZoneCmd(role)
	for _, sub := range tmp.Commands() {
		if sub.Name() == "list" {
			tmp.RemoveCommand(sub)
			return sub
		}
	}
	panic("tdnscli.NewZoneCmd has no \"list\" leaf")
}
